//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStream.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;AttachDbFilename=D:\\Personal\\Projects\\Shokh\\MyStream\\MyS" +
            "treamWeb\\App_Data\\MyStream.mdf;Persist Security Info=True;User ID=sa;Password=ja" +
            "nina")]
        public string MyStreamConnectionString {
            get {
                return ((string)(this["MyStreamConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=D:\\PERSONAL\\PROJECTS\\SHOKH\\MYSTREAM\\MYST" +
            "REAMWEB\\APP_DATA\\MYSTREAM.MDF;Integrated Security=True")]
        public string D__PERSONAL_PROJECTS_SHOKH_MYSTREAM_MYSTREAMWEB_APP_DATA_MYSTREAM_MDFConnectionString {
            get {
                return ((string)(this["D__PERSONAL_PROJECTS_SHOKH_MYSTREAM_MYSTREAMWEB_APP_DATA_MYSTREAM_MDFConnectionSt" +
                    "ring"]));
            }
        }
    }
}
